// Self-checking testbench for the ALU Decoder (provided scaffold).
// Same vector-driven style as the full adder testbench.
//
// Vector layout per line in aludecoder.tv (10 bits, underscores ignored):
//   {ALUOp[1:0], funct3[2:0], op5, funct75, ALUControlexpected[2:0]}
//     2        +  3         +  1  +  1     +  3                      = 10
//
// You normally do NOT edit this file; complete aludecoder.sv (and add
// vectors to aludecoder.tv if you wish). Ends with $finish and dumps a
// VCD for Vapor View.
module aludecoder_tb();

   logic clk, reset;

   logic [1:0] ALUOp;
   logic [2:0] funct3;
   logic       op5, funct75;
   logic [2:0] ALUControl, ALUControlexpected;

   logic [31:0] vectornum, errors;
   // bits [9:0] = vector; bit [10] = guard (1 = past the last vector).
   // The sim is 2-state (X collapses to 0), so end-of-vectors cannot be
   // detected with `=== 10'bx`; the guard bit is the 2-state-safe equivalent.
   logic [10:0] testvectors[10000:0];   // 7 input bits + 3 output bits + guard

   // Instantiate device under test.
   aludecoder dut(.ALUOp, .funct3, .op5,
                  .funct75, .ALUControl);

   // Clock: period of 10 time units.
   always begin
      clk = 1; #5;
      clk = 0; #5;
   end

   initial begin
      $dumpfile("waves/aludecoder.vcd");
      $dumpvars(0, aludecoder_tb);

      // Prefill with 1s so the guard bit ([10]) is set; $readmemb zero-fills
      // the guard bit on every line it loads.
      for (int i = 0; i <= 10000; i++) testvectors[i] = '1;
      $readmemb("aludecoderFixed.tv", testvectors);
      vectornum = 0;
      errors    = 0;
      reset = 1; #22; reset = 0;
   end

   // Apply vectors on rising edge.
   always @(posedge clk) begin
      #1;
      {ALUOp, funct3, op5, funct75, ALUControlexpected} = testvectors[vectornum][9:0];
   end

   // Check on falling edge.
   always @(negedge clk)
      if (~reset) begin
         if (ALUControl !== ALUControlexpected) begin
            $display("Error: ALUOp=%b funct3=%b op5=%b funct75=%b",
                     ALUOp, funct3, op5, funct75);
            $display("  ALUControl = %b (%b expected)",
                     ALUControl, ALUControlexpected);
            errors = errors + 1;
         end
         vectornum = vectornum + 1;
         if (testvectors[vectornum][10] === 1'b1) begin  // guard bit -> done
            $display("%d tests completed with %d errors", vectornum, errors);
            $finish;
         end
      end
endmodule
